import { Link } from "react-router-dom";
import SeoHead from "@/components/SeoHead";
import PageShell from "@/components/PageShell";
import { motion, Variants } from "framer-motion";

const LAST_UPDATED = "July 21, 2026";

export default function PrivacyPolicy() {
  const container: Variants = {
    hidden: { opacity: 0 },
    show: {
      opacity: 1,
      transition: {
        staggerChildren: 0.15,
        delayChildren: 0.2,
      },
    },
  };

  const item: Variants = {
    hidden: { opacity: 0, y: 20 },
    show: { opacity: 1, y: 0, transition: { duration: 0.8, ease: "easeOut" } },
  };

  return (
    <PageShell>
      <SeoHead
        title="Privacy Policy | Corbin Meier"
        description="Read Corbin Meier's privacy policy covering contact form data, analytics, retention, and your rights."
        path="/privacy-policy"
      />
      <motion.main
        variants={container}
        initial="hidden"
        animate="show"
        className="page-container"
      >
        <motion.header variants={item} className="w-full mb-16 text-center sm:text-left">
          <h1 className="text-h1 font-serif mb-6">Privacy Policy</h1>
          <p className="text-narrative">Last updated: {LAST_UPDATED}</p>
          <p className="text-sm text-muted mt-2">
            See also our{" "}
            <Link to="/terms-of-service" className="text-accent hover:underline">
              Terms of Service
            </Link>.
          </p>
        </motion.header>

        <motion.div variants={item} className="w-full space-y-10 text-muted leading-relaxed">
          <section>
            <h2 className="text-xl font-bold text-foreground mb-3">Information You Provide</h2>
            <p>
              The only information you choose to submit is gathered through the contact
              form - your first name, last name (optional), email address, phone number
              (optional), subject, and message. Nothing is submitted or transmitted unless
              you fill out and send that form.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground mb-3">Information Collected Automatically</h2>
            <p>
              Like most websites, this site's hosting infrastructure (Cloudflare Pages)
              automatically logs standard technical data for every visit - your IP
              address, browser/device user-agent string, requested URL, and timestamp.
              These logs exist purely for security, abuse prevention, and operational
              troubleshooting; they are generated and retained by Cloudflare's
              infrastructure under its own privacy policy, are not linked to your
              contact-form submissions, and are not used to build an advertising or
              tracking profile of you.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground mb-3">How It's Used</h2>
            <p>
              Information submitted through the contact form is used solely to respond to
              your inquiry: it is sent by email to Corbin Meier, and a confirmation email
              is sent back to the address you provided. This site does not persist
              contact-form submissions in a database - the data exists only as the email
              messages generated by your submission, stored securely within our email
              provider's mailbox infrastructure. It is not sold, shared with third parties
              for marketing, or used for any purpose beyond responding to your message.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground mb-3">Retention</h2>
            <p>
              Contact-form emails are retained in the associated mailbox for as long as
              needed to address your inquiry and for reasonable record-keeping afterward.
              Automatically collected technical logs (see above) are retained according to
              Cloudflare's standard log-retention windows, not indefinitely. You may
              request deletion of your contact-form correspondence at any time using the
              contact information below.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground mb-3">Cookies & Analytics</h2>
            <p>
              This site uses Cloudflare Web Analytics, a cookieless, privacy-respecting
              analytics service. It records aggregate page-view metrics - the page visited,
              referrer, approximate country, device type, browser, and operating system.
              It sets no cookies and stores nothing on your device, which is why you are
              not asked to dismiss a consent banner. It does not fingerprint you, does not
              track you across other websites, does not identify you personally, and is
              never tied to information submitted through the contact form.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground mb-3">Your Responsibility & Liability</h2>
            <p>
              All information submitted through this site's forms is provided voluntarily
              by you. By submitting the contact form, you agree that Corbin Meier is not
              liable for any issues arising from the information you choose to share,
              to the fullest extent permitted by law.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground mb-3">Contact</h2>
            <p>
              Questions about this policy, or requests to review or delete information you
              submitted, can be sent to{" "}
              <a href="mailto:contact@corbinmeier.net" className="text-accent hover:underline">
                contact@corbinmeier.net
              </a>.
            </p>
          </section>

          <p className="text-xs text-muted-foreground pt-6 border-t border-border">
            This policy is provided as a general good-faith summary and is not legal
            advice. Consult an attorney to confirm it meets your specific legal
            obligations.
          </p>
        </motion.div>
      </motion.main>
    </PageShell>
  );
}
